# Generated by Django 5.2.5 on 2025-08-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
