# Generated by Django 5.2.5 on 2025-09-03 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='excluido',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='usuario',
        ),
        migrations.AddField(
            model_name='agenda',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='atualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_deletadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
