# Generated by Django 5.2.5 on 2025-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_agenda_cancelada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='cancelada',
        ),
        migrations.AddField(
            model_name='agenda',
            name='status',
            field=models.CharField(choices=[('pendente', 'PEN'), ('marcado', 'MARC'), ('cancelado', 'CANCEL')], default='pendente', max_length=20),
        ),
    ]
