# Generated by Django 5.2.5 on 2025-08-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_remove_agenda_cancelada_agenda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='excluido',
            field=models.BooleanField(default=False),
        ),
    ]
